oligos/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required
from django.urls import include, path
from django.contrib import admin
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register('oligos', views.OligoViewset, 'oligos')
router.register('usages', views.UsageViewset, 'usages')

app_name = 'oligos'
urlpatterns = [
    # /oligos/
    path('', include(router.urls)),
    # path('', views.OligoListView.as_view(), name='index'),
    path('generic_search/', views.OligoSearchView.as_view(), name='generic_search'),
    # /oligos/<int:oligo_id>/
    path('<int:pk>/', views.OligoDetailView.as_view(), name='detail'),
    # /oligos/<int:oligo_id>/edit/
    path('<int:pk>/update/', permission_required('oligos.change_oligo')(views.OligoUpdate.as_view()), name='update'),
    # /oligos/<int:oligo_id>/delete/
    path('<int:pk>/delete/', permission_required('oligos.change_oligo')(views.OligoDelete.as_view()), name='delete'),
    # /oligos/<int:oligo_id>/clone/
    path('<int:pk>/clone/', views.clone, name='clone_oligo'),
    # /oligos/new/
    path('new/', views.OligoCreate.as_view(), name='new'),
    # /oligos/batch/
    path('batch/', views.batch, name='batch'),
    # /oligos/search/
    path('search/', views.search, name='search'),
    # /oligos/index/
    #url(r'^$', views.OligoListView.as_view(), name='index')
]

receptor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    # path('accounts/', include('accounts.urls')),
    path('api/auth/', include('accounts.api.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('oligos/', include('oligos.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load fontawesome_5 %}
<head>
  <title>Receptor</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  {% fontawesome_5_static %}
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>

<body>
  <div class="container-fluid h-100">
    <div class="row">
    	<div id="header">
    		{% include 'header.html' %}
    	</div>
    </div>
    <div class="row" id="fill-height">
      <div class="col-1" id="sidebar">
        {% include 'sidebar.html' %}
      </div>
      <div class="col-10" id="content">
        <br>
        {% block content %}{% endblock %}

          {% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
          {% endblock %}
        <br>
      </div>
    </div>
    <div class="row">
      <p id="footer"><i>Receptor</i> 2020. Thomas Oh and Abeer Eltanawy.</p>
    </div>
  </div>
</body>

templates/header.html
<ul class="nav navbar-nav navbar-right">
	{% if user.is_authenticated %}
			<li>Logged in as {{ user.username }}</li>>
	{% else %}
		<li><a href="/accounts/signup"><b>Sign Up</b></a></li>
		<li><a href="/accounts/login/"><b>Login</b></a></li>
	{% endif %}
</ul>

templates/home.html
{% extends "base.html" %}

{% block content %}

  <h2>Welcome to your Lab Receptor!</h2>
  <p>
    Receptor is a web-based application for managing lab data. Modules, or apps,
    are accessed via the sidebar on the left. Login information is shown in the
    upper-right corner of the page. For more information, please contact you
    department adminstrator.
  </p>

{% endblock %}

templates/sidebar.html
<nav class="navbar navbar-dark align-items-start py-2">
  <ul class="flex-md-column navbar-nav justify-content-between">
    <li class="nav-item">
      <a class="nav-link pl-0 text-nowrap" href="/"><span class="font-weight-bold">Home</span></a>
    </li>
		<li class="dropdown">
	    <a class="dropdown-toggle" id="menu" data-toggle="dropdown" href="#">Oligos
	    <span class="caret"></span></a>
	    <ul class="dropdown-menu" id="dropdown">
				<a a class="dropdown-item" href="/oligos/">View list</a>
	      <a a class="dropdown-item" href="{% url 'oligos:new' %}">Add new oligo</a>
	      <a class="dropdown-item disabled" href="#">Batch submission</a>
	      <a class="dropdown-item disabled" href="#">Sequence search</a>
	    </ul>
	  </li>
	</ul>
</nav>